export const TIPS = [
  '💡 Tip: You can set your availability for appointments in your profile settings.',
  '💡 Tip: Use hashtags in your posts to reach a wider audience.',
  '💡 Tip: You can create a shop to sell products or offer services.',
  '💡 Tip: Start a school to create courses and share your expertise.',
  '💡 Tip: Connect with other members to see their activity in your feed.',
  '💡 Tip: Need something? Post a request and let the community help.',
  '💡 Tip: You can save posts and items to your Saved list for later.',
  '💡 Tip: Create a project plan with milestones to track your progress.',
  '💡 Tip: Join groups to collaborate with people who share your interests.',
  '💡 Tip: Use the Planner to manage appointments and personal events.',
  '💡 Tip: You can accept crypto tips on your posts from the community.',
  '💡 Tip: Set up a courier service to offer delivery with your products.',
  '💡 Tip: Barter offers let you trade items without using cash.',
  '💡 Tip: Create events to gather your community around shared activities.',
  '💡 Tip: Use the search bar or press Cmd+K to quickly find anything.',
  '💡 Tip: Customize your profile with a bio and cover image.',
  '💡 Tip: You can set up donation addresses to receive direct crypto support.',
  '💡 Tip: Rentals let you earn from items you are not using daily.',
  '💡 Tip: Forum posts are a great way to start discussions.',
  '💡 Tip: Use templates to quickly set up a shop, school, or courier service.',
]
